---
apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbShare
metadata:
  name: first
spec:
  shareName: "First Share"
  readOnly: false
  browseable: false
  securityConfig: ugsecurity
  storage:
    pvc:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
