resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env
      value:
      - name: "SAMBA_OP_SMBD_CONTAINER_IMAGE"
        value: "quay.io/phlogistonjohn/samba-container:jjm-sxp"
      - name: "SAMBA_OP_SVC_WATCH_CONTAINER_IMAGE"
        value: "quay.io/phlogistonjohn/svcwatch:jjm-sxp"
  target:
    kind: Deployment
